version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dropshipping
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A src.jobs worker --loglevel=info
    volumes:
      - ../backend:/app
    depends_on:
      - backend
      - redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    command: flower --broker=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  pgdata:
